namespace: "${api_namespace}"
dockerhub: "sanketikahub"
replicaCount: 1
repository: "obsrv-api-service"
env: "${env}"
image_tag: 1.0.2
network:
  port: 3000
  targetport: 3000
SYSTEM_ENV: "${env}"
druid_service:
  DRUID_HOST: http://druid-raw-${env}-routers.druid-raw.svc
  DRUID_PORT: 8888
kafka_service:
  KAFKA_HOST: "kafka-headless.kafka.svc"
  KAFKA_PORT: 9092
  KAFKA_INITIAL_RETRY_TIME: 3000
  KAFKA_RETRIES: 5
  KAFKA_CONNECTION_TIMEOUT: 5000
  CLIENT_ID: "obsrv-apis"
postgres_service:
  POSTGRES_HOST: postgresql-hl.postgresql.svc
  POSTGRES_PORT: 5432
  POSTGRES_DATABASE: "obsrv"
  POSTGRES_USERNAME: "postgres"
  POSTGRES_PASSWORD: "postgres"
