---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-jobmanager
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-jobmanager
    release: monitoring
spec:
  selector:
    matchLabels:
      component: {{ .Release.Name }}-jobmanager
      app: {{ .Chart.Name }}
  endpoints:
  - port: prom
    interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-jobmanager-webui
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-jobmanager-webui
    release: monitoring
spec:
  selector:
    matchLabels:
      component: {{ .Release.Name }}-jobmanager-webui
      app: {{ .Chart.Name }}
  endpoints:
  - port: prom
    interval: 30s